version: '3'

volumes:
  postgres-data:
  redisdata:
  elasticsearch-data:
  qcat_static_files:

services:
  selenium:
    image: selenium/hub:3.11.0-dysprosium
    ports:
      - 4444:4444
      - 5900:5900

  postgres:
    image: camptocamp/postgres:9.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=qcat
      - POSTGRES_PASSWORD=qcat
      - APP_DB_USER=qcat
      - APP_DB_PASS=qcat
      - APP_DB_NAME=qcat
    networks:
      default:
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redisdata:/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: qcat:dev
    environment:
      # Environment variables for django are set in the entrypoint.sh script.
      - PYTHONPATH=/code/apps
    entrypoint: ["./entrypoint.sh"]
    # entrypoint: [".entrypoint.sh", "build"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
      - qcat_static_files:/code/static
      - /qcat_data/upload/:/upload
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - selenium
