# Generated by Django 3.2.4 on 2021-09-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_auto_20201020_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='translation',
            field=models.ForeignKey(limit_choices_to={'translation_type': 'category'}, on_delete=django.db.models.deletion.CASCADE, to='configuration.translation'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('key__keyword', 'country')), null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.value'),
        ),
        migrations.AlterField(
            model_name='key',
            name='translation',
            field=models.ForeignKey(limit_choices_to={'translation_type': 'key'}, on_delete=django.db.models.deletion.CASCADE, to='configuration.translation'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='translation',
            field=models.ForeignKey(blank=True, limit_choices_to={'translation_type': 'value'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.translation'),
        ),
        migrations.AlterField(
            model_name='value',
            name='translation',
            field=models.ForeignKey(limit_choices_to={'translation_type': 'value'}, on_delete=django.db.models.deletion.CASCADE, to='configuration.translation'),
        ),
    ]
